---
- name: Create directory for checkout owned by the local user
  ansible.builtin.file:
    path: "{{ git_dir }}"
    owner: "{{ ansible_user }}"
    state: directory
    mode: "0755"

- name: Git checkout
  ansible.builtin.git:
    repo: "git@github.com:farm-urban/fufarm_rpi_arduino_shield.git"
    dest: "{{ git_dir }}"
    accept_hostkey: true
  become: false

- name: Install arduino-cli and libraries
  ansible.builtin.command:
    cmd: "{{ git_dir }}/install_lib.sh"
    creates: /opt/arduino-cli/bin/arduino-cli
  become: false

- name: Upload arduino sketch to the board
  ansible.builtin.command:
    cmd: "../upload.sh"
    chdir: "{{ git_dir }}/rpi_arduino_shield"
  become: false

#
# MQTT-IO
#
- name: Install python virtualenv
  ansible.builtin.apt:
    cache_valid_time: 300 # 5 minutes
    pkg:
      - python3-virtualenv
    state: present

- name: Install mqtt-io python package
  ansible.builtin.pip:
    name:
      - paho-mqtt==1.6.1
      - mqtt-io
    #       - requests
    #       - pyyaml
    # virtualenv: "{{ ha_dir }}/py_venv"
    virtualenv: "{{ git_dir }}/py_venv"
    virtualenv_site_packages: true
  become: false

- name: Configure sensors as service
  ansible.builtin.template:
    src: templates/fusensors.service.j2
    dest: /etc/systemd/system/fusensors.service
    mode: "0644"

- name: Enable and unmask fusensors
  ansible.builtin.systemd:
    name: fusensors
    enabled: true
    masked: false
    state: started
