- name: Git checkout Home Assistant Edenic repository # noqa: latest
  ansible.builtin.git:
    repo: "git@github.com:farm-urban/{{ edenic_git_name }}.git"
    dest: "{{ edenic_ha_dir }}"
    accept_hostkey: true
  become: false

- name: Install python virtualenv
  ansible.builtin.apt:
    cache_valid_time: 300 # 5 minutes
    pkg:
      - python3-virtualenv
    state: present

- name: Install required python packages
  ansible.builtin.pip:
    name:
      - requests
      - pyyaml
      - paho-mqtt
    virtualenv: "{{ edenic_ha_dir }}/venv"
    virtualenv_site_packages: true
  become: false

- name: Configure sensors as service
  ansible.builtin.template:
    src: templates/edenic.service.j2
    dest: /etc/systemd/system/edenic.service
    mode: "0644"
    user: root

- name: Enable and unmask edenic.service
  ansible.builtin.systemd:
    name: edenic.service
    enabled: true
    masked: false
    daemon_reload: true
    state: started
