- name: Create directory for checkout owned by the local user
  ansible.builtin.file:
    path: "{{ edenic_ha_dir }}"
    owner: "{{ ansible_user }}"
    state: directory

- name: Install python virtualenv
  ansible.builtin.apt:
    cache_valid_time: 300 # 5 minutes
    pkg:
      - python3-virtualenv
    state: present

- name: Install required python packages
  ansible.builtin.pip:
    name:
      - requests
      - pyyaml
      - paho-mqtt
    virtualenv: "{{ edenic_ha_dir  }}/venv"
    virtualenv_site_packages: true
  become: false

# Copy in the files
- name: Copy in python file
  ansible.builtin.copy:
    src: "files/edenic_mqtt.py"
    dest: "{{ edenic_ha_dir }}"
    owner: "{{ ansible_user }}"

- name: Copy in yaml file
  ansible.builtin.copy:
    src: "files/edenic.yml"
    dest: "{{ edenic_ha_dir }}"
    owner: "{{ ansible_user }}"

- name: Configure sensors as service
  ansible.builtin.template:
    src: templates/edenic.service.j2
    dest: /etc/systemd/system/edenic.service

- name: Enable and unmask edenic.service
  ansible.builtin.systemd:
    name: edenic.service
    enabled: true
    masked: false
    daemon_reload: true
    state: started
