- name: Create directory for checkout owned by the local user
  ansible.builtin.file:
    path: "{{ edenic_ha_dir }}"
    owner: "{{ ansible_user }}"
    state: directory

- name: Install python virtualenv
  ansible.builtin.apt:
    cache_valid_time: 300 # 5 minutes
    pkg:
      - python3-virtualenv
    state: present

- name: Install required python packages
  ansible.builtin.pip:
    name:
      - requests
      - pyyaml
      - paho-mqtt
    virtualenv: "{{ edenic_ha_dir  }}/venv"
    virtualenv_site_packages: true
  become: false

# Create files to autostart bluelab
- name: Create systemd conf directory
  ansible.builtin.file:
    path: "~/.config/systemd/user"
    state: directory
    owner: "{{ ansible_user }}"
  become: false

# Script to autostart bluelab
- name: Create bluelab.service script
  ansible.builtin.template:
    src: templates/edenic.service.j2
    dest: "~/.config/systemd/user/edenic.service"
    owner: "{{ ansible_user }}"
  become: false

- name: Enable and unmask edenic.service
  ansible.builtin.systemd:
    name: edenic.service
    scope: user
    enabled: true
    masked: false
    daemon_reload: true
    state: started
  become: false
