- name: Git checkout Home Assistant Edenic repository
  ansible.builtin.git:
    repo: "git@github.com:farm-urban/homeassistant_edenic.git"
    dest: "{{ edenic_ha_dir }}"
    owner: "{{ ansible_user }}"
    accept_hostkey: true
  become: false

- name: Install python virtualenv
  ansible.builtin.apt:
    cache_valid_time: 300 # 5 minutes
    pkg:
      - python3-virtualenv
    state: present

- name: Install required python packages
  ansible.builtin.pip:
    name:
      - requests
      - pyyaml
      - paho-mqtt
    virtualenv: "{{ edenic_ha_dir  }}/venv"
    virtualenv_site_packages: true
  become: false
## TODO
# - name: Configure sensors as service
#   ansible.builtin.template:
#     src: templates/edenic.service.j2
#     dest: /etc/systemd/system/edenic.service

# - name: Enable and unmask edenic.service
#   ansible.builtin.systemd:
#     name: edenic.service
#     enabled: true
#     masked: false
#     daemon_reload: true
#     state: started
