---
- name: Setup access-point/client
  hosts: local
  gather_facts: no
  remote_user: pi
  become: yes # remote_user and/or become?
  vars_files:
    - files/variables.yml
  roles:
    - ap-client
  # tasks:
  # - name: get mask
  #   blockinfile:
  #       path: ~/jens
  #       block: |
  #         # this is my code
  #         {{ wifi_ap_address | ansible.utils.ipsubnet(24) }}
  #       create: true
