---
- name: Setup access-point/client
  hosts: local
  remote_user: pi
  become: yes # remote_user and/or become?
  vars_files:
    - files/variables.yml
  roles:
    - ap-client
  # tasks:
  # - name: Print the gateway for each host when defined
  #   ansible.builtin.debug:
  #     msg: Got ansible facts {{ ansible_facts }}
  #   when: ansible_facts.wlan0.active

