---
- name: Setup access-point/client
  hosts: local
  remote_user: pi
  become: yes
  # gather_facts: no
  roles:
  #   - rpi-setup
  #   - tailscale-install
    - webcam
  # post_tasks:
  #   # Seems to be the only way to set variables conditionally as set_fact
  #   # doesn't respect tags
  #   - ansible.builtin.import_role:
  #       name: ap-client
  #     vars:
  #       access_point: false
  #       external_wifi: false
  #       tailscale: true

  # - name: Print the gateway for each host when defined
  #   ansible.builtin.debug:
  #     msg: ansible_distribution_release {{ ansible_distribution_release }}
