---
- name: Setup access-point/client
  hosts: farm
  remote_user: pi
  become: yes
  # gather_facts: no
  roles:
    - rpi-setup
    - tailscale-install
    - webcam
    - fu-sensors
    - bluelab
  post_tasks:
    - ansible.builtin.import_role:
        name: ap-client
      vars:
        access_point: true
        external_wifi: true
        tailscale: true

  # - name: Print the gateway for each host when defined
  #   ansible.builtin.debug:
  #     msg: ansible_distribution_release {{ ansible_distribution_release }}
