---
- name: Setup access-point/client
  hosts: tmrewrpi
  remote_user: fu
  become: yes
  gather_facts: yes
  roles:
    # - rpi-setup
    # - tailscale-install
    # # - webcam
    # - fu-sensors
    # - bluelab
    - home-assistant
  # post_tasks:
  #   - ansible.builtin.import_role:
  #       name: ap-client
  #     vars:
  #       access_point: true
  #       external_wifi: true
  #       tailscale: true

  # - name: Print the gateway for each host when defined
  #   ansible.builtin.debug:
  #     msg: ansible_distribution_release {{ ansible_distribution_release }}
