---
# See group_vars: all.yml for variables determining which roles are run
- name: Setup access-point/client
  hosts: jenspi
  remote_user: fu
  become: yes
  gather_facts: yes
  roles:
    - { role: rpi-setup, when: do_rpi_setup }
    - { role: tailscale-install, when: do_tailscale_install }
    - { role: docker, when: do_docker }
    - { role: home-assistant, when: do_home_assistant }
    - { role: ap-client, when: do_ap_client }
    # - { role: bluelab, when: do_bluelab }
    # - { role: usb-webcam, when: do_usb_webcam }
    # - { role: fu-sensors, when: do_fu_sensors }

  # post_tasks:
  #   - ansible.builtin.import_role:
  #       name: ap-client
  #     vars:
  #       access_point: true
  #       external_wifi: true
  #       tailscale: true

  # - name: Print the gateway for each host when defined
  #   ansible.builtin.debug:
  #     msg: ansible_distribution_release {{ ansible_distribution_release }}
