- name: Git checkout Hydroponincs control # noqa: latest
  ansible.builtin.git:
    repo: "git@github.com:farm-urban/fufarm_hydro.git"
    dest: "{{ hydrocontrol_dir }}"
    accept_hostkey: true
  become: false

- name: Create virtual environment and install requirements
  ansible.builtin.command:
    cmd: ./activate_venv.sh
    chdir: "{{ hydrocontrol_dir }}"
    creates: "{{ hydrocontrol_venv }}"
  become: false

- name: Configure mqtt-io as a service
  ansible.builtin.template:
    src: templates/mqtt-io.service.j2
    dest: /etc/systemd/system/mqtt-io.service
    mode: "0644"

- name: Enable and unmask mqtt-io service
  ansible.builtin.systemd:
    name: mqtt-io
    enabled: true
    masked: false
    state: started
    daemon_reload: true

- name: Configure hydrocontrol webserver as a service
  ansible.builtin.template:
    src: templates/hydrocontrol.service.j2
    dest: /etc/systemd/system/hydrocontrol.service
    mode: "0644"

- name: Enable and unmask hydrocontrol webserver service
  ansible.builtin.systemd:
    name: hydrocontrol
    enabled: true
    masked: false
    state: started
    daemon_reload: true
