---
#
# Home Assistant
#
- name: Git checkout Home Assistant # noqa: latest
  ansible.builtin.git:
    repo: "git@github.com:farm-urban/fufarm_ha_docker.git"
    dest: "{{ ha_dir }}"
    accept_hostkey: true
  become: false

- name: Set permissions of mqttuser file
  ansible.builtin.file:
    path: "{{ ha_dir }}/mosquitto/config/mqttuser"
    state: file
    mode: "0700"

#
# Tapo Webcam
#
- name: Git checkout tapo_control # noqa: latest
  ansible.builtin.git:
    repo: "https://github.com/JurajNyiri/HomeAssistant-Tapo-Control.git"
    dest: "/home/{{ ansible_user }}/HomeAssistant-Tapo-Control"

# - name: Create custom_components directory if it doesn't already exist
#   ansible.builtin.file:
#     path: /root/config/custom_components
#     state: directory

- name: Copy tapo_control directory to config directory
  ansible.builtin.copy:
    src: /home/{{ ansible_user }}/HomeAssistant-Tapo-Control/custom_components/tapo_control
    dest: "{{ ha_dir }}/config/custom_components"
    remote_src: true
    mode: "0744"
