---
- name: Install required software packages
  ansible.builtin.apt:
    cache_valid_time: 300 # time in seconds => 5 minutes
    pkg:
      - ca-certificates
      - curl
    state: present

# Install Docker
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

# Raspberry Pi OS (64-bit) is based on Debian
- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
    state: present

- name: Install Docker and related packages
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - docker-ce
      # - docker-ce-cli
      # - containerd.io
      # # - docker-buildx-plugin
      # - docker-compose-plugin
    state: present


- name: Create "docker" group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add remote user to "docker" group
  ansible.builtin.user:
    name: fu
    groups: docker
    append: yes

