# Set up a usb webcam
---
- name: Install motion
  ansible.builtin.apt:
    cache_valid_time: 300 # time in seconds => 5 minutes
    pkg:
      - motion
    state: present
  when: ansible_facts.wlan0.active # Could just ignore errors?

- name: Create motion log directory
  ansible.builtin.file:
    path: /var/log/motion
    owner: motion
    state: directory

- name: Create motion conf directory
  ansible.builtin.file:
    path: "{{ motion_conf_dir }}"
    owner: motion
    state: directory

- name: Set all our variables at end of the file
  ansible.builtin.blockinfile:
    path: /etc/motion/motion.conf
    block: |
      log_level 5
      picture_output off
      movie_output off
      stream_localhost off
      camera_dir {{ motion_conf_dir }}

- name: Find path to webcam
  ansible.builtin.find:
    paths: /dev/v4l/by-id/
    patterns: "^.*(?i)webcam.*index0$"
    # patterns: "usb-Trust_Webcam_Trust_Webcam_Trust_Webcam-video-index0"
    file_type: link
    use_regex: true # Python regexp
  register: webcam_devs
  failed_when: webcam_devs.matched < 1

# - name: Print debug 
#   ansible.builtin.debug:
#     msg: Got file {{ webcam_devs.files[0].path }}

- name: Set cam1 path
  ansible.builtin.set_fact:
    cam1_path: "{{ webcam_devs.files[0].path }}"

- name: Create camera config file
  ansible.builtin.template:
    src: templates/camera1.conf.j2
    dest: "{{ motion_conf_dir }}/camera1.conf"

- name: Reload motion
  ansible.builtin.systemd:
    name: wpa_supplicant
    state: started

# Not sure why we don't need to reconfigure the firewall to allow stream_port1