---
- name: Install required software packages
  ansible.builtin.apt:
    cache_valid_time: 300 # time in seconds => 5 minutes
    pkg:
      #- dhcpcd # Present by default
      - dnsmasq
      - hostapd
      - iptables-persistent  # auto-loads iptables rules on boot
    state: present
  when: ansible_facts.wlan0.active # Could just ignore errors?

#
# Wireless interfaces
#
# Create wifi_ap_interface - maybe should do this in dhcpcd.conf?
- name: Configure ap interface
  ansible.builtin.template:
    src: templates/ap.j2
    dest: /etc/network/interfaces.d/ap

## For now we assume that the wifi client has been set up
## look at /usr/bin/raspi-config - it seems to use wpa_cli to set everything up
# Set up wifi_client_interface configuration
# - name: Backup wpa_supplicant.conf file prior to deletion
#   copy:
#     remote_src: True
#     src: /etc/wpa_supplicant/wpa_supplicant.conf
#     dest: /etc/wpa_supplicant/wpa_supplicant.conf.bak

# - name: Delete wpa_supplicant file
#   file:
#     path: /etc/wpa_supplicant/wpa_supplicant.conf
#     state: absent

# - name: create wireless interface file
#   template:
#     src: templates/wpa_supplicant-interface.conf.j2
#     dest: /etc/wpa_supplicant/wpa_supplicant-{{ wifi_client_interface }}.conf
#   notify:
#   - reload wpa_supplicant

- name: create wireless interface file
  template:
    src: templates/wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
  notify:
  - Reload wpa_supplicant

- name: Configure dhcpcd
  ansible.builtin.blockinfile:
    path: /etc/dhcpcd.conf
    block: |
      # noarp to speed things up: https://wiki.archlinux.org/title/dhcpcd#Speed_up_DHCP_by_disabling_ARP_probing
      noarp
      interface {{ eth_interface }}
          static ip_address={{ eth_interface_address }}/24
      interface {{ wifi_ap_interface }}
          static ip_address={{ wifi_ap_address }}/24
          nohook wpa_supplicant

- name: Create ap.service script
  template:
    src: templates/ap.service.j2
    dest: /etc/systemd/system/ap.service
  when: not external_wifi

- name: Start ap and enable for boot
  ansible.builtin.systemd:
    name: ap.service
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
  when: not external_wifi

# Access point configuration
- name: Configure dnsmasq
  ansible.builtin.template:
    src: templates/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf

- name: Configure hostapd
  ansible.builtin.template:
    src: templates/hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf

# Firewall configuration
## rpi docs recommend: /etc/sysctl.d/routed-ap.conf
- name: Enable IP forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

## Configure firewall with iptables
- name: Install iptables rules
  template:
    src: templates/iptables.v4.j2
    dest: /etc/iptables/rules.v4

# This will load a state from a file, with a rollback in case of access loss
- name: restore firewall state from a file
  community.general.iptables_state:
    state: restored
    path: /etc/iptables/rules.v4
  async: "{{ ansible_timeout }}"
  poll: 0
  # notify:
  #   - Restart network # Do this at end rather then restarting each individual service

- name: Enable and unmask dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    enabled: yes
    masked: no

# Only in case of external wifi as other we use the ap.service script
- name: Enable and unmask hostapd
  ansible.builtin.systemd:
    name: hostapd
    enabled: yes
    masked: no
  when: external_wifi

# Scripts to login to tailscale on reboot
- name: Create tailscale-start.service script
  template:
    src: templates/tailscale-start.service.j2
    dest: /etc/systemd/system/tailscale-start.service
  when: tailscale

- name: Enable and unmask tailscale-start
  ansible.builtin.systemd:
    name: tailscale-start
    enabled: yes
    masked: no
    state: started
  when: tailscale

