---
# https://forums.raspberrypi.com/viewtopic.php?t=357998
# https://www.baeldung.com/linux/nmcli-wap-sharing-internet

# sudo nmcli con add type wifi ifname wlan0 mode ap con-name SENSOR_AP ssid FUsensors \
#   connection.autoconnect yes \
#   ipv4.method shared \
#   ipv4.addresses 192.168.5.1/24 \
#   802-11-wireless.band bg \
#   802-11-wireless.channel 7 \
#   ipv6.method disabled \
#   wifi-sec.key-mgmt wpa-psk \
#   wifi-sec.psk 'FARM123!'

- name: Create an AP mode wifi connection
  community.general.nmcli:
    type: wifi
    ifname: wlan0
    conn_name: SENSOR_AP
    ssid: FUsensors
    method4: shared
    method6: disabled
    ip4: 192.168.5.1/24
    wifi:
      mode: ap
      band: bg
      channel: 7
    wifi_sec:
      key-mgmt: wpa-psk
      psk: 'FARM123!'
    autoconnect: true
    state: present

# sudo nmcli con up SENSOR_AP

