---
# https://forums.raspberrypi.com/viewtopic.php?t=357998
# https://www.baeldung.com/linux/nmcli-wap-sharing-internet

# sudo nmcli con add type wifi ifname wlan0 mode ap con-name SENSOR_AP ssid FUsensors \
#   connection.autoconnect yes \
#   ipv4.method shared \
#   ipv4.addresses 192.168.5.1/24 \
#   802-11-wireless.band bg \
#   802-11-wireless.channel 7 \
#   ipv6.method disabled \
#   wifi-sec.key-mgmt wpa-psk \
#   wifi-sec.psk 'FARM123!'

- name: Create an AP mode wifi connection
  community.general.nmcli:
    type: wifi
    ifname: "{{ wifi_ap_interface }}"
    conn_name: "{{ ap_ssid }}"
    ssid: "{{ ap_ssid }}"
    method4: shared
    method6: disabled
    ip4: "{{ wifi_ap_address + '/24' }}"
    wifi:
      mode: ap
      band: bg
      channel: "{{ ap_channel }}"
    wifi_sec:
      key-mgmt: wpa-psk
      psk: "{{ ap_password }}"
    autoconnect: true
    state: present

# https://fedoramagazine.org/internet-connection-sharing-networkmanager/
# sudo nmcli con add type ethernet ifname eth0 con-name ETH_SHARED \
#   connection.autoconnect yes \
#   ipv4.method shared \
#   ipv4.addresses 192.168.4.1/24 
- name: Share internet and allow login via ethernet port
  community.general.nmcli:
    type: ethernet
    ifname: "{{ eth_interface }}"
    conn_name: ETH_SHARED
    method4: shared
    method6: disabled
    ip4: "{{ eth_interface_address + '/24' }}"
    autoconnect: true
    state: present

# https://wiki.archlinux.org/title/NetworkManager
- name: Set IP address for devices
  ansible.builtin.template:
    src: templates/static-ips.conf.j2
    dest: /etc/NetworkManager/dnsmasq-shared.d/static-ips.conf