---
# - name: Clean up APT
#   apt:
#     update_cache: yes
#     upgrade: dist
#     autoremove: yes
#     autoclean: yes
#   become: yes

- name: Install required software packages
  ansible.builtin.apt:
    cache_valid_time: 300 # 5 minutes
    pkg:
      #- dhcpcd # Present by default
      - dnsmasq
      - hostapd
      - ufw
    state: present

- name: Enable and unmask hostapd
  ansible.builtin.systemd:
    name: hostapd
    enabled: yes
    masked: no

- name: Enable and unmask dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    enabled: yes
    masked: no

- name: Enable UFW
  community.general.ufw:
    state: enabled

#
# Wireless interfaces
#
# Create wifi_ap_interface
# This doesn't seem to come up without a reboot - not sure why
- name: Create udev file for ap interface
  ansible.builtin.template:
    src: templates/90-wireless.rules.j2
    dest: /etc/udev/rules.d/90-wireless.rules

- name: Configure ap interface
  ansible.builtin.template:
    src: templates/ap.j2
    dest: /etc/network/interfaces.d/ap


## For now we assume that the wifi client has been set up
## look at /usr/bin/raspi-config - it seems to use wpa_cli to set everything up
# Set up wifi_client_interface configuration
# - name: Backup wpa_supplicant.conf file prior to deletion
#   copy:
#     remote_src: True
#     src: /etc/wpa_supplicant/wpa_supplicant.conf
#     dest: /etc/wpa_supplicant/wpa_supplicant.conf.bak

# - name: Delete wpa_supplicant file
#   file:
#     path: /etc/wpa_supplicant/wpa_supplicant.conf
#     state: absent

# - name: create wireless interface file
#   template:
#     src: templates/wpa_supplicant-interface.conf.j2
#     dest: /etc/wpa_supplicant/wpa_supplicant-{{ wifi_client_interface }}.conf
#   notify:
#   - reload wpa_supplicant


# Access point configuration
- name: Configure dnsmasq
  ansible.builtin.template:
    src: templates/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf

- name: Configure hostapd
  ansible.builtin.template:
    src: templates/hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf

  # - name: Creating hostapd deamon file
  #   copy:
  #     dest: "/your path"
  #     content: |
  #       # {{ ansible_managed }}
  #       DAEMON_CONF="/etc/hostapd/hostapd.conf"

- name: Configure dhcpcd
  ansible.builtin.blockinfile:
    path: /etc/dhcpcd.conf
    block: |
      interface {{ wifi_ap_interface }}
          #static ip_address={{ wifi_ap_address }}/24 # Not required currently as we use the interface file
          nohook wpa_supplicant


# Firewall configuration
## rpi docs recommend: /etc/sysctl.d/routed-ap.conf
- name: Enable IP forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

## Configure firewall with ufw or iptables
- name: 'Allow docker DEFAULT_FORWARD_POLICY=ACCEPT'
  community.general.ufw:
      direction: routed
      default: allow
      route: yes

- name: add NAT to ufw
  blockinfile:
    path: /etc/ufw/before.rules
    block: |
      # NAT table rules
      *nat
      :POSTROUTING ACCEPT [0:0]
      # Forward traffic through interface
      --append POSTROUTING --source {{ wifi_ap_address | ansible.utils.ipsubnet(24) }} --out-interface {{ wifi_ap_interface }} --jump MASQUERADE
      # don't delete the 'COMMIT' line or these nat table rules won't be processed
      COMMIT
    insertbefore: "^# Don't delete these required lines"
  notify:
    - Restart ufw
  # notify:
  #   - Restart network # Do this at end rather then restarting each individual service

#sudo iptables --table nat -A POSTROUTING --out-interface wlan0 --source 192.168.4.0/24 -j MASQUERADE
#sudo iptables --append FORWARD --in-interface uap0 --out-interface  wlan0 --match state --state RELATED,ESTABLISHED --jump ACCEPT
#sudo iptables --append FORWARD --in-interface wlan0 --out-interface  uap0 --jump ACCEPT

